// Code generated by ent, DO NOT EDIT.

package http

import (
	"net/http"
	"strings"

	"github.com/mailru/easyjson"
	"github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent"
	account "github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/account"
	"github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/permission"
	"github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/refreshtoken"
	role "github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/role"
	"go.uber.org/zap"
)

// Create creates a new ent.Account and stores it in the database.
func (h AccountHandler) Create(w http.ResponseWriter, r *http.Request) {
	l := h.log.With(zap.String("method", "Create"))
	// Get the post data.
	var d AccountCreateRequest
	if err := easyjson.UnmarshalFromReader(r.Body, &d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		BadRequest(w, "invalid json string")
		return
	}
	// Save the data.
	b := h.client.Account.Create()
	if d.Username != nil {
		b.SetUsername(*d.Username)
	}
	if d.Password != nil {
		b.SetPassword(*d.Password)
	}
	if d.Email != nil {
		b.SetEmail(*d.Email)
	}
	if d.PhoneNumber != nil {
		b.SetPhoneNumber(*d.PhoneNumber)
	}
	if d.OAuthType != nil {
		b.SetOAuthType(*d.OAuthType)
	}
	if d.Role != nil {
		b.SetRoleID(*d.Role)
	}
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		default:
			l.Error("could not create account", zap.Error(err))
			InternalServerError(w, nil)
		}
		return
	}
	// Store id of fresh entity to log errors for the reload.
	id := e.ID
	// Reload entry.
	q := h.client.Account.Query().Where(account.ID(e.ID))
	ret, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.String("id", id.String()))
			NotFound(w, msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.String("id", id.String()))
			BadRequest(w, msg)
		default:
			l.Error("could not read account", zap.Error(err), zap.String("id", id.String()))
			InternalServerError(w, nil)
		}
		return
	}
	l.Info("account rendered", zap.String("id", id.String()))
	easyjson.MarshalToHTTPResponseWriter(NewAccount2555118887View(ret), w)
}

// Create creates a new ent.Permission and stores it in the database.
func (h PermissionHandler) Create(w http.ResponseWriter, r *http.Request) {
	l := h.log.With(zap.String("method", "Create"))
	// Get the post data.
	var d PermissionCreateRequest
	if err := easyjson.UnmarshalFromReader(r.Body, &d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		BadRequest(w, "invalid json string")
		return
	}
	// Validate the data.
	errs := make(map[string]string)
	if d.PermissionName == nil {
		errs["permissionName"] = `missing required field: "permissionName"`
	} else if err := permission.PermissionNameValidator(*d.PermissionName); err != nil {
		errs["permissionName"] = strings.TrimPrefix(err.Error(), "permission: ")
	}
	if d.URI == nil {
		errs["uri"] = `missing required field: "uri"`
	} else if err := permission.URIValidator(*d.URI); err != nil {
		errs["uri"] = strings.TrimPrefix(err.Error(), "permission: ")
	}
	if d.Method == nil {
		errs["method"] = `missing required field: "method"`
	} else if err := permission.MethodValidator(*d.Method); err != nil {
		errs["method"] = strings.TrimPrefix(err.Error(), "permission: ")
	}
	if len(errs) > 0 {
		l.Info("validation failed", zapFields(errs)...)
		BadRequest(w, errs)
		return
	}
	// Save the data.
	b := h.client.Permission.Create()
	if d.PermissionName != nil {
		b.SetPermissionName(*d.PermissionName)
	}
	if d.URI != nil {
		b.SetURI(*d.URI)
	}
	if d.Method != nil {
		b.SetMethod(*d.Method)
	}
	if d.Permissions != nil {
		b.AddPermissionIDs(d.Permissions...)
	}
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		default:
			l.Error("could not create permission", zap.Error(err))
			InternalServerError(w, nil)
		}
		return
	}
	// Store id of fresh entity to log errors for the reload.
	id := e.ID
	// Reload entry.
	q := h.client.Permission.Query().Where(permission.ID(e.ID))
	ret, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.String("id", id.String()))
			NotFound(w, msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.String("id", id.String()))
			BadRequest(w, msg)
		default:
			l.Error("could not read permission", zap.Error(err), zap.String("id", id.String()))
			InternalServerError(w, nil)
		}
		return
	}
	l.Info("permission rendered", zap.String("id", id.String()))
	easyjson.MarshalToHTTPResponseWriter(NewPermission4235299754View(ret), w)
}

// Create creates a new ent.RefreshToken and stores it in the database.
func (h RefreshTokenHandler) Create(w http.ResponseWriter, r *http.Request) {
	l := h.log.With(zap.String("method", "Create"))
	// Get the post data.
	var d RefreshTokenCreateRequest
	if err := easyjson.UnmarshalFromReader(r.Body, &d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		BadRequest(w, "invalid json string")
		return
	}
	// Save the data.
	b := h.client.RefreshToken.Create()
	if d.Username != nil {
		b.SetUsername(*d.Username)
	}
	if d.Token != nil {
		b.SetToken(*d.Token)
	}
	if d.ExpiredAt != nil {
		b.SetExpiredAt(*d.ExpiredAt)
	}
	if d.RoleName != nil {
		b.SetRoleName(*d.RoleName)
	}
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		default:
			l.Error("could not create refresh-token", zap.Error(err))
			InternalServerError(w, nil)
		}
		return
	}
	// Store id of fresh entity to log errors for the reload.
	id := e.ID
	// Reload entry.
	q := h.client.RefreshToken.Query().Where(refreshtoken.ID(e.ID))
	ret, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.String("id", id.String()))
			NotFound(w, msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.String("id", id.String()))
			BadRequest(w, msg)
		default:
			l.Error("could not read refresh-token", zap.Error(err), zap.String("id", id.String()))
			InternalServerError(w, nil)
		}
		return
	}
	l.Info("refresh-token rendered", zap.String("id", id.String()))
	easyjson.MarshalToHTTPResponseWriter(NewRefreshToken3828610044View(ret), w)
}

// Create creates a new ent.Role and stores it in the database.
func (h RoleHandler) Create(w http.ResponseWriter, r *http.Request) {
	l := h.log.With(zap.String("method", "Create"))
	// Get the post data.
	var d RoleCreateRequest
	if err := easyjson.UnmarshalFromReader(r.Body, &d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		BadRequest(w, "invalid json string")
		return
	}
	// Save the data.
	b := h.client.Role.Create()
	if d.RoleName != nil {
		b.SetRoleName(*d.RoleName)
	}
	if d.Description != nil {
		b.SetDescription(*d.Description)
	}
	if d.Permissions != nil {
		b.AddPermissionIDs(d.Permissions...)
	}
	if d.Accounts != nil {
		b.AddAccountIDs(d.Accounts...)
	}
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		default:
			l.Error("could not create role", zap.Error(err))
			InternalServerError(w, nil)
		}
		return
	}
	// Store id of fresh entity to log errors for the reload.
	id := e.ID
	// Reload entry.
	q := h.client.Role.Query().Where(role.ID(e.ID))
	ret, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.String("id", id.String()))
			NotFound(w, msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.String("id", id.String()))
			BadRequest(w, msg)
		default:
			l.Error("could not read role", zap.Error(err), zap.String("id", id.String()))
			InternalServerError(w, nil)
		}
		return
	}
	l.Info("role rendered", zap.String("id", id.String()))
	easyjson.MarshalToHTTPResponseWriter(NewRole736703411View(ret), w)
}
