// Code generated by ent, DO NOT EDIT.

package http

import (
	"github.com/google/uuid"
	account "github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/account"
	"github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/refreshtoken"
	role "github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/role"
)

// Payload of a ent.Account create request.
type AccountCreateRequest struct {
	Username    *string            `json:"username"`
	Password    *string            `json:"password"`
	Email       *string            `json:"email"`
	PhoneNumber *string            `json:"phoneNumber"`
	OAuthType   *account.OAuthType `json:"oAuthType"`
	Role        *uuid.UUID         `json:"role"`
}

// Payload of a ent.Account update request.
type AccountUpdateRequest struct {
	Username    *string            `json:"username"`
	Password    *string            `json:"password"`
	Email       *string            `json:"email"`
	PhoneNumber *string            `json:"phoneNumber"`
	OAuthType   *account.OAuthType `json:"oAuthType"`
	Role        *uuid.UUID         `json:"role"`
}

// Payload of a ent.Permission create request.
type PermissionCreateRequest struct {
	PermissionName *string     `json:"permissionName"`
	URI            *string     `json:"uri"`
	Method         *string     `json:"method"`
	Permissions    []uuid.UUID `json:"permissions"`
}

// Payload of a ent.Permission update request.
type PermissionUpdateRequest struct {
	PermissionName *string     `json:"permissionName"`
	URI            *string     `json:"uri"`
	Method         *string     `json:"method"`
	Permissions    []uuid.UUID `json:"permissions"`
}

// Payload of a ent.RefreshToken create request.
type RefreshTokenCreateRequest struct {
	Username  *string                `json:"username"`
	Token     *string                `json:"token"`
	ExpiredAt *string                `json:"expiredAt"`
	RoleName  *refreshtoken.RoleName `json:"roleName"`
}

// Payload of a ent.RefreshToken update request.
type RefreshTokenUpdateRequest struct {
	Username  *string                `json:"username"`
	Token     *string                `json:"token"`
	ExpiredAt *string                `json:"expiredAt"`
	RoleName  *refreshtoken.RoleName `json:"roleName"`
}

// Payload of a ent.Role create request.
type RoleCreateRequest struct {
	RoleName    *role.RoleName `json:"roleName"`
	Description *string        `json:"description"`
	Permissions []uuid.UUID    `json:"permissions"`
	Accounts    []uuid.UUID    `json:"accounts"`
}

// Payload of a ent.Role update request.
type RoleUpdateRequest struct {
	RoleName    *role.RoleName `json:"roleName"`
	Description *string        `json:"description"`
	Permissions []uuid.UUID    `json:"permissions"`
	Accounts    []uuid.UUID    `json:"accounts"`
}
