// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/predicate"
	"github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/refreshtoken"
)

// RefreshTokenUpdate is the builder for updating RefreshToken entities.
type RefreshTokenUpdate struct {
	config
	hooks    []Hook
	mutation *RefreshTokenMutation
}

// Where appends a list predicates to the RefreshTokenUpdate builder.
func (rtu *RefreshTokenUpdate) Where(ps ...predicate.RefreshToken) *RefreshTokenUpdate {
	rtu.mutation.Where(ps...)
	return rtu
}

// SetUsername sets the "username" field.
func (rtu *RefreshTokenUpdate) SetUsername(s string) *RefreshTokenUpdate {
	rtu.mutation.SetUsername(s)
	return rtu
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableUsername(s *string) *RefreshTokenUpdate {
	if s != nil {
		rtu.SetUsername(*s)
	}
	return rtu
}

// SetToken sets the "token" field.
func (rtu *RefreshTokenUpdate) SetToken(s string) *RefreshTokenUpdate {
	rtu.mutation.SetToken(s)
	return rtu
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableToken(s *string) *RefreshTokenUpdate {
	if s != nil {
		rtu.SetToken(*s)
	}
	return rtu
}

// SetExpiredAt sets the "expiredAt" field.
func (rtu *RefreshTokenUpdate) SetExpiredAt(s string) *RefreshTokenUpdate {
	rtu.mutation.SetExpiredAt(s)
	return rtu
}

// SetNillableExpiredAt sets the "expiredAt" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableExpiredAt(s *string) *RefreshTokenUpdate {
	if s != nil {
		rtu.SetExpiredAt(*s)
	}
	return rtu
}

// SetRoleName sets the "roleName" field.
func (rtu *RefreshTokenUpdate) SetRoleName(rn refreshtoken.RoleName) *RefreshTokenUpdate {
	rtu.mutation.SetRoleName(rn)
	return rtu
}

// SetNillableRoleName sets the "roleName" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableRoleName(rn *refreshtoken.RoleName) *RefreshTokenUpdate {
	if rn != nil {
		rtu.SetRoleName(*rn)
	}
	return rtu
}

// Mutation returns the RefreshTokenMutation object of the builder.
func (rtu *RefreshTokenUpdate) Mutation() *RefreshTokenMutation {
	return rtu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rtu *RefreshTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, rtu.sqlSave, rtu.mutation, rtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rtu *RefreshTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := rtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rtu *RefreshTokenUpdate) Exec(ctx context.Context) error {
	_, err := rtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtu *RefreshTokenUpdate) ExecX(ctx context.Context) {
	if err := rtu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rtu *RefreshTokenUpdate) check() error {
	if v, ok := rtu.mutation.RoleName(); ok {
		if err := refreshtoken.RoleNameValidator(v); err != nil {
			return &ValidationError{Name: "roleName", err: fmt.Errorf(`ent: validator failed for field "RefreshToken.roleName": %w`, err)}
		}
	}
	return nil
}

func (rtu *RefreshTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := rtu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(refreshtoken.Table, refreshtoken.Columns, sqlgraph.NewFieldSpec(refreshtoken.FieldID, field.TypeUUID))
	if ps := rtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rtu.mutation.Username(); ok {
		_spec.SetField(refreshtoken.FieldUsername, field.TypeString, value)
	}
	if value, ok := rtu.mutation.Token(); ok {
		_spec.SetField(refreshtoken.FieldToken, field.TypeString, value)
	}
	if value, ok := rtu.mutation.ExpiredAt(); ok {
		_spec.SetField(refreshtoken.FieldExpiredAt, field.TypeString, value)
	}
	if value, ok := rtu.mutation.RoleName(); ok {
		_spec.SetField(refreshtoken.FieldRoleName, field.TypeEnum, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rtu.mutation.done = true
	return n, nil
}

// RefreshTokenUpdateOne is the builder for updating a single RefreshToken entity.
type RefreshTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RefreshTokenMutation
}

// SetUsername sets the "username" field.
func (rtuo *RefreshTokenUpdateOne) SetUsername(s string) *RefreshTokenUpdateOne {
	rtuo.mutation.SetUsername(s)
	return rtuo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableUsername(s *string) *RefreshTokenUpdateOne {
	if s != nil {
		rtuo.SetUsername(*s)
	}
	return rtuo
}

// SetToken sets the "token" field.
func (rtuo *RefreshTokenUpdateOne) SetToken(s string) *RefreshTokenUpdateOne {
	rtuo.mutation.SetToken(s)
	return rtuo
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableToken(s *string) *RefreshTokenUpdateOne {
	if s != nil {
		rtuo.SetToken(*s)
	}
	return rtuo
}

// SetExpiredAt sets the "expiredAt" field.
func (rtuo *RefreshTokenUpdateOne) SetExpiredAt(s string) *RefreshTokenUpdateOne {
	rtuo.mutation.SetExpiredAt(s)
	return rtuo
}

// SetNillableExpiredAt sets the "expiredAt" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableExpiredAt(s *string) *RefreshTokenUpdateOne {
	if s != nil {
		rtuo.SetExpiredAt(*s)
	}
	return rtuo
}

// SetRoleName sets the "roleName" field.
func (rtuo *RefreshTokenUpdateOne) SetRoleName(rn refreshtoken.RoleName) *RefreshTokenUpdateOne {
	rtuo.mutation.SetRoleName(rn)
	return rtuo
}

// SetNillableRoleName sets the "roleName" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableRoleName(rn *refreshtoken.RoleName) *RefreshTokenUpdateOne {
	if rn != nil {
		rtuo.SetRoleName(*rn)
	}
	return rtuo
}

// Mutation returns the RefreshTokenMutation object of the builder.
func (rtuo *RefreshTokenUpdateOne) Mutation() *RefreshTokenMutation {
	return rtuo.mutation
}

// Where appends a list predicates to the RefreshTokenUpdate builder.
func (rtuo *RefreshTokenUpdateOne) Where(ps ...predicate.RefreshToken) *RefreshTokenUpdateOne {
	rtuo.mutation.Where(ps...)
	return rtuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rtuo *RefreshTokenUpdateOne) Select(field string, fields ...string) *RefreshTokenUpdateOne {
	rtuo.fields = append([]string{field}, fields...)
	return rtuo
}

// Save executes the query and returns the updated RefreshToken entity.
func (rtuo *RefreshTokenUpdateOne) Save(ctx context.Context) (*RefreshToken, error) {
	return withHooks(ctx, rtuo.sqlSave, rtuo.mutation, rtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rtuo *RefreshTokenUpdateOne) SaveX(ctx context.Context) *RefreshToken {
	node, err := rtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rtuo *RefreshTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := rtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtuo *RefreshTokenUpdateOne) ExecX(ctx context.Context) {
	if err := rtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rtuo *RefreshTokenUpdateOne) check() error {
	if v, ok := rtuo.mutation.RoleName(); ok {
		if err := refreshtoken.RoleNameValidator(v); err != nil {
			return &ValidationError{Name: "roleName", err: fmt.Errorf(`ent: validator failed for field "RefreshToken.roleName": %w`, err)}
		}
	}
	return nil
}

func (rtuo *RefreshTokenUpdateOne) sqlSave(ctx context.Context) (_node *RefreshToken, err error) {
	if err := rtuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(refreshtoken.Table, refreshtoken.Columns, sqlgraph.NewFieldSpec(refreshtoken.FieldID, field.TypeUUID))
	id, ok := rtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RefreshToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refreshtoken.FieldID)
		for _, f := range fields {
			if !refreshtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != refreshtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rtuo.mutation.Username(); ok {
		_spec.SetField(refreshtoken.FieldUsername, field.TypeString, value)
	}
	if value, ok := rtuo.mutation.Token(); ok {
		_spec.SetField(refreshtoken.FieldToken, field.TypeString, value)
	}
	if value, ok := rtuo.mutation.ExpiredAt(); ok {
		_spec.SetField(refreshtoken.FieldExpiredAt, field.TypeString, value)
	}
	if value, ok := rtuo.mutation.RoleName(); ok {
		_spec.SetField(refreshtoken.FieldRoleName, field.TypeEnum, value)
	}
	_node = &RefreshToken{config: rtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rtuo.mutation.done = true
	return _node, nil
}
