// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/account"
	"github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/permission"
	"github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/refreshtoken"
	"github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/role"
	"github.com/tuanngoo192003/gateway-demo-go/authservice/domain/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[0].Descriptor()
	// account.DefaultID holds the default value on creation for the id field.
	account.DefaultID = accountDescID.Default.(func() uuid.UUID)
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescPermissionName is the schema descriptor for permissionName field.
	permissionDescPermissionName := permissionFields[1].Descriptor()
	// permission.PermissionNameValidator is a validator for the "permissionName" field. It is called by the builders before save.
	permission.PermissionNameValidator = permissionDescPermissionName.Validators[0].(func(string) error)
	// permissionDescURI is the schema descriptor for uri field.
	permissionDescURI := permissionFields[2].Descriptor()
	// permission.URIValidator is a validator for the "uri" field. It is called by the builders before save.
	permission.URIValidator = permissionDescURI.Validators[0].(func(string) error)
	// permissionDescMethod is the schema descriptor for method field.
	permissionDescMethod := permissionFields[3].Descriptor()
	// permission.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	permission.MethodValidator = permissionDescMethod.Validators[0].(func(string) error)
	// permissionDescID is the schema descriptor for id field.
	permissionDescID := permissionFields[0].Descriptor()
	// permission.DefaultID holds the default value on creation for the id field.
	permission.DefaultID = permissionDescID.Default.(func() uuid.UUID)
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescID is the schema descriptor for id field.
	refreshtokenDescID := refreshtokenFields[0].Descriptor()
	// refreshtoken.DefaultID holds the default value on creation for the id field.
	refreshtoken.DefaultID = refreshtokenDescID.Default.(func() uuid.UUID)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleFields[0].Descriptor()
	// role.DefaultID holds the default value on creation for the id field.
	role.DefaultID = roleDescID.Default.(func() uuid.UUID)
}
